services:

  php:
    restart: always
    image: local/php:latest
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php
    volumes:
      - ./:/var/www/html:rw
    ports:
      - "${HTTP_PORT:-8000}:8000"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "${PG_PORT:-5432}:5432"

volumes:
  database_data: