controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

legacy:
    resource:
        path: ../src/LegacyBridge
        namespace: App\LegacyBridge
    type: attribute
